---
- hosts: all
 
  gather_facts: yes
  ignore_errors: true
  vars: 
    user_name: edwige2029
    group_name: devops
  vars_files:
    - variables.yml 
  tasks:
    - name: Check the time
      command: datenhdtkh
#      when: ansible_distribution == "edwige" or ansible_processor_nproc == 2
    - name: create user edwige
      user:
         name: "{{user_name}}"
         comment: Edwige Admin
    - name: create group
      group:
         name: "{{group_name}}"
         state: present 
      become: true
    - name: Install package
      package:
        name: "{{pkg_name}}"
        state: present  